In [1]:
import numpy as np

In [5]:
a = np.array([1,2,3])
a

array([1, 2, 3])

List와 indexing

In [7]:
A = [1,'b','c']

In [8]:
A[1]

'b'

In [9]:
type(A)

list

In [10]:
type(A[1])

str

In [11]:
B = [1,2,3,4,5,6]

In [15]:
B[1:4]#1이상 4미만 

[2, 3, 4]

In [16]:
type(B[1:4])

list

In [17]:
B[3:6][1]

5

List in List

In [18]:
B = [1,2,'c',[1,3,4]]

In [20]:
List_B = B[3]
List_B

[1, 3, 4]

In [21]:
List_B[1]

3

In [22]:
B[3][1]

3

In [23]:
C = [[1,2,3,4],[3,[12,4,5,65],'c',10],'a']

In [24]:
C[1][1][2]

5

- 수학에서의 벡터의 기본 표기 단위
   - Column(열)vector로 표기하는 것이 관습



- Python에서 벡터의 기본 단위
    - 다른 구조체와 메모리 구조상 Row(행) vector로 표기하는 것이 관습
     -   X = np.array([1, 2, 3])

## Python에서 Maxtrix 생성하기


In [37]:
x1 = np.array([[5],[6]])
x1

array([[5],
       [6]])

In [38]:
x1.ndim

2

In [27]:
X = np.array([[5,6,8],[6,7,4]])
X

array([[5, 6, 8],
       [6, 7, 4]])

In [28]:
X2 = np.array([[5,6,8],[6,2]])#차원이 맞지 않음
X2

<ipython-input-28-d7b128f3b210>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  X2 = np.array([[5,6,8],[6,2]])


array([list([5, 6, 8]), list([6, 2])], dtype=object)

In [29]:
X.ndim#차원

2

In [30]:
a = np.array([12,3,4])
a.ndim

1

In [33]:
b = np.array([[12,3,4]])
b.ndim

2

- Check Type
    - dtype

In [34]:
X.dtype

dtype('int64')

In [35]:
type(X)

numpy.ndarray

## Python 에서의 Vector

- 1-D vector
    - row vector에서만 표현 가능
- 2-D vector
    - row,Column vector 모두 표현 가능

## (수학) 차원 확인 명령어

In [39]:
X = np.array([[1,2,3],[4,5,6]])

In [40]:
X.shape

(2, 3)

### Matrix 연산자

- 전치
    - x.T
- reshpae

In [41]:
X

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
X.shape

(2, 3)

In [42]:
X.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [44]:
X.reshape(3,2)#전치와는 다른 연산 수행 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
X.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### Vector transpose 주의점
- transpose 연산자는 1D Array는 변환하지 못한다

In [46]:
a = np.array([1,2,3])
a.T

array([1, 2, 3])

In [48]:
a.shape

(3,)

In [47]:
b = np.array([[1,2,3]])
b.T

array([[1],
       [2],
       [3]])

In [50]:
a.reshape(3,1)#1차원 전치 가능

array([[1],
       [2],
       [3]])

In [52]:
x1 = np.array([[5],[6],[7]])
x1

array([[5],
       [6],
       [7]])

In [53]:
x2 = np.array([[6],[7],[5]])
x2

array([[6],
       [7],
       [5]])

In [55]:
x2.ndim

2

In [56]:
x2.shape

(3, 1)

In [58]:
x1T = x1.T
x1T

array([[5, 6, 7]])

In [59]:
x2T = x2.T
x2T

array([[6, 7, 5]])

In [60]:
x1TT = x1.reshape(1,3)
x1TT

array([[5, 6, 7]])

In [62]:
x2TT = x2.reshape(1,3)
x2TT

array([[6, 7, 5]])

* 'vstack' ((vertical) 수직으로 쌓다)

In [64]:
X = np.vstack([x1T,x2T])
X

array([[5, 6, 7],
       [6, 7, 5]])

* 'hstack' ((horizontal) 수평으로 쌓다)

In [66]:
Xhstack = np.hstack([x1T,x2T])
Xhstack

array([[5, 6, 7, 6, 7, 5]])

In [67]:
Xhstack2 = np.hstack([x1,x2])
Xhstack2

array([[5, 6],
       [6, 7],
       [7, 5]])

In [72]:
onevec = np.ones((3,1),int)
onevec

array([[1],
       [1],
       [1]])

In [74]:
zerovec = np.zeros((2,3))
zerovec

array([[0., 0., 0.],
       [0., 0., 0.]])

In [76]:
np.arange(0,3,0.5)#3미만

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [78]:
np.linspace(0,3,10)# 0 ~ 3까지 동일한 간격으로 10개 나눠라

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [79]:
np.linspace(0,4,4)

array([0.        , 1.33333333, 2.66666667, 4.        ])

### Radom Generaton
- random.rand

In [82]:
d = 2*np.random.rand(1,10)-1
d

array([[-0.69013355,  0.47947704, -0.72767062, -0.96842138, -0.22741136,
        -0.6535918 , -0.00674288, -0.38913479, -0.20736155,  0.71845789]])

### 정규분포 (가우시안 분포)

- 정규분포 평균 = 1, 분산 = 4 생성

In [86]:
e = 2*np.random.randn(3,4) + 1
e

array([[ 5.0324786 ,  4.55877827, -0.26400135,  2.84509242],
       [ 0.91531092,  0.01805925,  1.81346475,  0.9192121 ],
       [-1.15722259,  2.7551151 ,  2.51083541, -0.49861962]])