# 유용한 강좌
- [CS229 tutorial 한글번역](http://aikorea.org/cs231n/python-numpy-tutorial/)
- 
[Scipy-lectures](https://scipy-lectures.org/)
    - [Numpy](https://scipy-lectures.org/intro/numpy/index.html)
    - [Operations](https://scipy-lectures.org/intro/numpy/operations.html)

# 0. 사전준비
`import`를 잊지 마세요!

In [2]:
import numpy as np

# 1. 행렬

* 다음 $A\in \mathbb{R}^{3\times 4}$ 행렬을 고려합시다:
\begin{align*}
A = \begin{bmatrix}
1 & 2 & 3 & 4 \\
11 & 12 & 10 & 14 \\
6 & 7 & 4 & 20 
\end{bmatrix}
\end{align*}

* $A$ 행렬의 각 column (열)을 $a^{(i)}\in \mathbb{R}^3$이라고 하겠습니다. 즉, 
\begin{align*}
A = \begin{bmatrix}
a^{(1)} & a^{(2)} & a^{(3)} & a^{(4)} 
\end{bmatrix}
\end{align*}
과 같이 표현 됩니다. 더 자세하게 한번더 설명하자면
\begin{align*}
a^{(1)} = \begin{bmatrix}
1\\
11\\
6
\end{bmatrix}, \quad
a^{(2)} = \begin{bmatrix}
2\\
12\\
7
\end{bmatrix}, \quad \ldots \quad,
a^{(4)} = \begin{bmatrix}
4\\
14\\
20
\end{bmatrix}
\end{align*}


## Problem 1

1. $A$ 행렬을 (3,4) ndarray로 만들어서 `A`라는 변수로 저장하세요. List에 직접 숫자를 기입하여 ndarray로 변환할 것


In [41]:
# 1-1 답

A = np.array([[1,2,3,4],[11,12,10,14],[6,7,4,20]])

print('A=', A)
print('A.shape=', A.shape)

A= [[ 1  2  3  4]
 [11 12 10 14]
 [ 6  7  4 20]]
A.shape= (3, 4)


연습. 행렬 (벡터)의 전치 연습
위 $A$ 행렬의 전치를 `A.T`를 통해서 구하세요

In [8]:
A.T

print('A.T = ', A.T)

A.T =  [[ 1 11  6]
 [ 2 12  7]
 [ 3 10  4]
 [ 4 14 20]]


2. $a^{(1)}$, $a^{(2)}$, $a^{(3)}$, $a^{(4)}$ 벡터를 (3,1) ndarray로 만들어서 `a1`, `a2`, `a3`, `a4` 라는 변수로 저장하세요. 
- 직접 숫자를 기입하지 말고 `A[index]`와 같이 index를 활용하여 구하세요.
- `a1`등의 차원이 column vector로 저장되도록 하세요 (reshape)


In [82]:
a11 = np.hstack([A[0][0], A[1][0], A[2][0]])
a11.shape
a11
#a11.reshape(3,1)


array([ 1, 11,  6])

In [83]:
# 1-2 답
a1 = np.hstack([A[0][0], A[1][0], A[2][0]])
a1 = a1.reshape(3,1)

a2 = np.hstack([A[0][1], A[1][1], A[2][1]])
a2 = a2.reshape(3,1)

a3 = np.vstack([A[0][2], A[1][2], A[2][2]])
a3 = a3.reshape(3,1)

a4 = np.vstack([A[0][3], A[1][3], A[2][3]])
a4 = a4.reshape(3,1)
print('a1=', a1)
print('a2=', a2)
print('a3=', a3)
print('a4=', a4)

a1= [[ 1]
 [11]
 [ 6]]
a2= [[ 2]
 [12]
 [ 7]]
a3= [[ 3]
 [10]
 [ 4]]
a4= [[ 4]
 [14]
 [20]]


3. $a^{(1)}$의 전치 (transpose), 즉 $(a^{(1)})^T$를 구하세요

In [84]:
# 1-3 답
answer = a1.T
print('a1의 transpose = ', answer)

a1의 transpose =  [[ 1 11  6]]


4. $B\in \mathbb{R}^{4\times 3}$라는 행렬을 다음과 같이 정의합니다:

\begin{align*}
B = \begin{bmatrix}
(a^{(1)})^T \\
(a^{(2)})^T \\
(a^{(3)})^T \\
(a^{(4)})^T 
\end{bmatrix}
\end{align*}

위에서 구한 `a1`, `a2`, `a3`, `a4`를 이용하여 `B`라는 변수에 $B$ 행렬을 저장하세요. 전치와 `np.vstack`, `np.concatenate`등을 사용하세요.

In [88]:
# 1-4 답
B = np.vstack([a1.T,a2.T,a3.T,a4.T])
print('B = ', B)
print('B.shape = ', B.shape)

B =  [[ 1 11  6]
 [ 2 12  7]
 [ 3 10  4]
 [ 4 14 20]]
B.shape =  (4, 3)


(확인) $A^T = B$가 성립하나요? 

In [86]:
print('Is A.T == B', A.T == B)

Is A.T == B [[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# 2. 행렬의 곱

* 행렬 곱은 다음과 같은 함수를 사용합니다.

`np.matmul(A, B)` 또는 `np.mm(A, B)`

* 벡터 $a\in\mathbb{R}^n$, $b^\in\mathbb{R}^n$ 간의 내적
\begin{align*}
a^Tb
\end{align*}
은 $(1\times n)$행렬과 $(n\times 1)$행렬간의 '행렬곱' 일 뿐이라는 것을 잊지 마세요.

* 즉, numpy에서는 내적을 위한 함수를 따로 정의하지 않습니다.

* 아래 문제에서는 $x\in\mathbb{R}^3$ 벡터를 사용합니다. 아래셀에서 `x`라는 벡터로 정의됩니다


In [92]:
x = np.array([0.5, 0.3, 0.2]).reshape(-1,1)
print('x=', x)
print('x.shape=', x.shape)

x= [[0.5]
 [0.3]
 [0.2]]
x.shape= (3, 1)


# Problem 2

1. 1번 문제에서 에서 구한 $a^{(i)}$, $i=1,2,3$과 $x$를 내적한 값을 각각 구하세요.

 - $(a^{(1)})^T x$는 `a1_ip_x`라는 변수에 저장
 - $(a^{(2)})^T x$는 `a2_ip_x`라는 변수에 저장
 - $(a^{(3)})^T x$는 `a3_ip_x`라는 변수에 저장
 - $(a^{(4)})^T x$는 `a4_ip_x`라는 변수에 저장

In [103]:
# 2-1 답 작성
a1_ip_x = np.matmul(a1.T,x)
print('a1_ip_x=', a1_ip_x)

a2_ip_x = np.matmul(a2.T,x)
print('a2_ip_x=', a2_ip_x)

a3_ip_x = np.matmul(a3.T,x)
print('a3_ip_x=', a3_ip_x)

a4_ip_x = np.matmul(a4.T,x)
print('a4_ip_x=', a4_ip_x)

a1_ip_x= [[5.]]
a2_ip_x= [[6.]]
a3_ip_x= [[5.3]]
a4_ip_x= [[10.2]]


2. 이번 문제의 목적은 
\begin{align*}
Bx = \begin{bmatrix}
(a^{(1)})^Tx\\
(a^{(2)})^Tx\\
(a^{(3)})^Tx\\
(a^{(4)})^Tx
\end{bmatrix}
\end{align*}
를 확인하는데 있습니다. 즉, 좌변의 연산이 우변의 연산과 같다는 것을 확인하려는 것입니다. (글로 풀어서 얘기하면, 좌변의 정의는 두 행렬 ($B$와 $x$)의 행렬곱이고, 우변은 $B$ 행렬의 row vector들과 $x$벡터의 내적을 차례대로 한 것을 벡터로 저장한 것이죠).

$Bx$를 구하고, `Bx`라는 변수에 저장하세요. `np.matmul`등을 활용하세요.


In [106]:
# 2-2 답 작성

B0_ip_x = np.matmul(B[0],x)
B1_ip_x = np.matmul(B[1],x)
B2_ip_x = np.matmul(B[2],x)
B3_ip_x = np.matmul(B[3],x)

Bx = np.vstack([B0_ip_x,B1_ip_x,B2_ip_x,B3_ip_x])


print('Bx=', Bx)

Bx= [[ 5. ]
 [ 6. ]
 [ 5.3]
 [10.2]]


3. 2-1번에서 구한 `a1_ip_x`, `a2_ip_x`, `a3_ip_x`, `a4_ip_x`을 원소로하는 (4,1) ndarray를 만들고 `aTx`라는 이름으로 저장하세요 (`np.vstack` 또는 `np.concatenate` 활용하면 되겠죠?). 
아래를 확인하세요

`Bx==aTx`

In [107]:
# 2-3 답 작성
aTx = np.vstack([a1_ip_x,a2_ip_x,a3_ip_x,a4_ip_x])
print('aTx = ', aTx)
print('aTx.shape = ', aTx.shape)

aTx =  [[ 5. ]
 [ 6. ]
 [ 5.3]
 [10.2]]
aTx.shape =  (4, 1)


In [108]:
print('Is Bx==aTx?', Bx==aTx)

Is Bx==aTx? [[ True]
 [ True]
 [ True]
 [ True]]


(해석) 여러개의 내적 값을 하나하나 (또는 for loop을 통해서) 구하지 않고, `np.matmul` 함수 한줄로 구할 수 있답니다. 이는 실제 for loop을 통해서 여러개의 내적을 구하는 것보다 편리할 뿐만 아니라, 처리속도 또한 상당히 빠릅니다. 관심있는 학생은 random하게 여러개의 벡터를 구해서 for loop으로 내적한 총 시간과, `matmul`을 활용해서 계산한 시간을 비교해보세요.

4. 다음은 $B$ 행렬의 각 column들을 $b^{(i)}\in\mathbb{R}^{4\times 1}$, $i=1,2,3$ 이라고 부르겠습니다. 앞으로 수업에서 아래와 같이 구조를 세세하게 알리지 않더라도 윗 글이 아래와 같은 것을 표현한다는 것을 다시한번 알아두도록 합시다:

\begin{align*}
B = [b^{(1)}, b^{(2)}, b^{(3)}] = \begin{bmatrix}
1 & 11 & 6 \\
2 & 12 & 7  \\
3 & 10 & 4  \\
4 & 14 & 20 
\end{bmatrix}
\end{align*}

- $B$행렬의 각 column들을 $x$벡터의 원소를 계수로 선형 결합하세요. 즉, 다음을 구합니다:

\begin{align*}
x_1 b^{(1)} + x_2 b^{(2)} + x_3 b^{(3)}
\end{align*}

- 여기서 $x_i$, $i=1,2,3$은
\begin{align*}
x = \begin{bmatrix}
x_1 \\
x_2 \\
x_3 
\end{bmatrix}
\end{align*}
입니다.

위 값을 `lincomb_B_by_x`라고 저장하세요. 역시 위에서 저장한 `B` 행렬과 `x` 벡터에 indexing을 활용하세요. 결정적인 힌트로 $b^{(1)}$은 `B[:,0]`를 활용하면 되겠지만, 다시 한번 강조하는 `shape`를 주의하세요. 마찬가지로 $x_1=$`x[0]`를 활용하면 되겠죠?

In [113]:
# 2-4 답 작성
lincomb_B_by_x = np.matmul(B[:5],x[:5])
print('lincomb_B_by_x = ', lincomb_B_by_x)
print('lincomb_B_by_x = ', lincomb_B_by_x.shape)

lincomb_B_by_x =  [[ 5. ]
 [ 6. ]
 [ 5.3]
 [10.2]]
lincomb_B_by_x =  (4, 1)


(Check) 아래 수식이 성립하나요?

\begin{align*}
Bx = x_1 b^{(1)} + x_2 b^{(2)} + x_3 b^{(3)}
\end{align*}

In [114]:
print('Is Bx == lincomb_B_by_x ?', Bx == lincomb_B_by_x)

Is Bx == lincomb_B_by_x ? [[ True]
 [ True]
 [ True]
 [ True]]
